export const POPULARATTHEBOXOFFICE = 'POPULARATTHEBOXOFFICE';
export const PREMIERESFORTHEWHOLEFAMILY = 'PREMIERESFORTHEWHOLEFAMILY'; 
export const PREMIERESMUSTHAVEATTHEBOXOFFICE = 'PREMIERESMUSTHAVEATTHEBOXOFFICE';
export const SPANISHPREMIERES = 'SPANISHPREMIERES';
export const IFYOUMISSED = 'IFYOUMISSED';
export const OURFAVORITESOFTHEWEEK = 'OURFAVORITESOFTHEWEEK';
export const MOVIEID = 'MOVIEID';